-- Gmail Integration Schema
-- Adds tables for email accounts, messages, replies, and settings

-- Email Accounts (stores OAuth tokens per user)
CREATE TABLE IF NOT EXISTS email_accounts (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    provider VARCHAR(50) DEFAULT 'gmail',
    email_address VARCHAR(255) NOT NULL,
    access_token TEXT,
    refresh_token TEXT,
    token_expires_at TIMESTAMPTZ,
    is_connected BOOLEAN DEFAULT true,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(user_id, email_address)
);

CREATE INDEX IF NOT EXISTS idx_email_accounts_user ON email_accounts(user_id);
CREATE INDEX IF NOT EXISTS idx_email_accounts_connected ON email_accounts(is_connected);

-- Email Messages (stores fetched emails)
CREATE TABLE IF NOT EXISTS email_messages (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    account_id UUID NOT NULL REFERENCES email_accounts(id) ON DELETE CASCADE,
    message_id VARCHAR(255) NOT NULL,
    thread_id VARCHAR(255),
    from_email VARCHAR(255),
    from_name VARCHAR(255),
    subject TEXT,
    body TEXT,
    snippet TEXT,
    received_at TIMESTAMPTZ,
    is_read BOOLEAN DEFAULT false,
    is_processed BOOLEAN DEFAULT false,
    created_at TIMESTAMPTZ DEFAULT NOW(),
    UNIQUE(account_id, message_id)
);

CREATE INDEX IF NOT EXISTS idx_email_messages_account ON email_messages(account_id);
CREATE INDEX IF NOT EXISTS idx_email_messages_processed ON email_messages(is_processed);
CREATE INDEX IF NOT EXISTS idx_email_messages_received ON email_messages(received_at DESC);

-- Email Replies (stores AI-generated replies)
CREATE TABLE IF NOT EXISTS email_replies (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    message_id UUID NOT NULL REFERENCES email_messages(id) ON DELETE CASCADE,
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    persona_id UUID REFERENCES personas(id) ON DELETE SET NULL,
    reply_text TEXT NOT NULL,
    confidence INTEGER,
    mode VARCHAR(20),  -- 'manual', 'auto'
    sent BOOLEAN DEFAULT false,
    sent_at TIMESTAMPTZ,
    created_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_replies_message ON email_replies(message_id);
CREATE INDEX IF NOT EXISTS idx_email_replies_user ON email_replies(user_id);
CREATE INDEX IF NOT EXISTS idx_email_replies_sent ON email_replies(sent);

-- Email Settings (auto-reply configuration per user)
CREATE TABLE IF NOT EXISTS email_settings (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE UNIQUE,
    auto_reply_enabled BOOLEAN DEFAULT false,
    mode VARCHAR(20) DEFAULT 'manual',  -- 'manual', 'auto', 'hybrid'
    filters JSONB DEFAULT '{"skipPromotions": true, "skipAutoGenerated": true}',
    schedule JSONB DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_email_settings_user ON email_settings(user_id);

-- Comments
COMMENT ON TABLE email_accounts IS 'Stores Gmail OAuth tokens for each user';
COMMENT ON TABLE email_messages IS 'Stores fetched emails from Gmail';
COMMENT ON TABLE email_replies IS 'Stores AI-generated email replies';
COMMENT ON TABLE email_settings IS 'Stores auto-reply configuration per user';
